### ISSUE TITLE
le_output broken

### ISSUE THREAD

**Issue by jacintodavila** [mcalejo/TaxKB#30]
reasoner:myClause2/3 is not properly reading the KB from a Taxlog .pl file. Therefore, kp_loader:kp_predicate_mention/3 fails and the output is empty.  Please, review and advise.

**Comment by mcalejo** [comment]
That was fixed recently in https://github.com/mcalejo/TaxKB/commit/984034237f6b5e8d9c8a484ebec9102a44d8fbd5 

Works, for example, for https://taxlog.logicalcontracts.com/p/cgt_affiliates.pl

If an example exists which fails please reopen this with it

**Comment by jacintodavila** [comment]
This is great! Thank you.
